q = ['SELECT ' ...
    '(CAST(m0.value AS DECIMAL (5 , 1 ))) AS Xstage, ' ...
    '(CAST(m1.value AS DECIMAL (5 , 1 ))) AS Ystage, ' ...
    '(CAST(m2.value AS DECIMAL (5 , 1 ))) AS Zstage ' ...
'FROM ' ...
'    external_files f ' ...
'        JOIN ' ...
'    external_meta_info m ON f.id = m.file_id ' ...
'        AND m.name = "data_type" ' ...
'        AND m.value = "raw" ' ...
'        JOIN ' ...
'    external_location l ON f.location = l.id ' ...
'        JOIN ' ...
'    external_meta_info m0 ON f.id = m0.file_id AND m0.name = "Xstage" ' ...
'        JOIN ' ...
'    external_meta_info m1 ON f.id = m1.file_id AND m1.name = "Ystage" ' ...
'        JOIN ' ...
'    external_meta_info m2 ON f.id = m2.file_id AND m2.name = "Zstage" ' ...
'WHERE ' ...
'    f.study_id = 77 ' ...
'        AND f.StudyUID IN ("1.2.826.0.1.3680043.8.498.52227911456223521834834") ' ...
];
dbc.execute(py.str(q));
res = dbc.fetchall();
stages=[];
i=1;
for st=res
    for j=1:3
       % keyboard
        stages(i,j)=double(py.float(cell(cell(st){1}){j}));
    end
    i=i+1;
end
figure(1);
plot(stages(:,1),stages(:,2),'o'); xlabel('Xstage'); ylabel('Ystage');