function Series_list = queryStudyUID(dbc,StudyUID,metastudyid)
q=py.str(['SELECT f.id,f.SeriesUID,m0.value as SeriesDescription,m1.value as AcquisitionsType,group_concat(m2.value) as Acq_nr,m3.value as SeriesNumber,m5.value as BGSeries ' ...
   'FROM external_files f ' ...
   'JOIN external_meta_info m0 on m0.file_id=f.id and m0.name="Series Description" ' ...
   'LEFT JOIN external_meta_info m1 on m1.file_id=f.id and m1.name="AcquisitionsType" ' ...
   'LEFT JOIN external_meta_info m2 on m2.file_id=f.id and m2.name="acquisition_number" ' ...
   'LEFT JOIN external_meta_info m3 on m3.file_id=f.id and m3.name="Series Number" ' ...  
   'LEFT JOIN external_meta_info m4 on f.id=m4.file_id and m4.name="file_modified" ' ...
   'LEFT JOIN external_meta_info m5 on f.id=m5.file_id and m5.name="BG Series Instance UID" ' ...   
   'where f.study_id=%s and f.StudyUID=%s ' ...
   'group by SeriesUID ' ...
   'order by cast(m3.value as unsigned), cast(m4.value as datetime) '
  ]);
v=py.list({metastudyid,StudyUID});
dbc.execute(q,v);
Series_list=dbc.fetchtodict();